services:
  puzzle-laser-generator:
    build: .
    image: puzzle-laser-generator:latest
    pull_policy: never
    container_name: puzzle-laser-generator
    restart: unless-stopped
    ports:
      - "5052:80"
